name: Build StosDebug IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List project
        run: |
          xcodebuild \
            -project StosDebug.xcodeproj \
            -list

      - name: Build
        run: |
          xcodebuild \
            -project StosDebug.xcodeproj \
            -scheme StosDebug \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Create IPA
        run: |
          mkdir Payload
          cp -R build/Build/Products/Release-iphoneos/StosDebug.app Payload/StosDebug.app
          zip -r StosDebug.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: StosDebug-IPA
          path: StosDebug.ipa
